template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "thai1261"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-tha"
__UND2C__ = "th"
__UNDEFINED__ = "Thai"
__UND__ = "tha"
